name: "Issue → ブランチ＆PR 自動化"

on:
  issues:
    types: [opened]

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-gemini/gemini-cli-action@main
        id: gemini_cli_action
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            /background Issue内容を解析し、新規 Python モジュール + pytest テストを生成
            Issue Title: ${{ github.event.issue.title }}
            Issue Body: ${{ github.event.issue.body }}
      - name: Checkout new branch
        run: |
          BRANCH_NAME=$(echo ${{ steps.gemini_cli_action.outputs.branch_name }})
          git checkout $BRANCH_NAME
      - name: Create branch & PR
        run: |
          gh auth login --with-token < <(echo ${{ secrets.GITHUB_TOKEN }})
          gh pr create \
            --title "feat: ${{ github.event.issue.title }}" \
            --body "自動生成 PR\n\nIssue: #${{ github.event.issue.number }}" \
            --base main

