name: "Issue → ブランチ＆PR 自動化"

on:
  issues:
    types: [opened]

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-gemini/gemini-cli-action@main
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            /background Issue内容を解析し、新規 Python モジュール + pytest テストを生成
            Issue Title: ${{ github.event.issue.title }}
            Issue Body: ${{ github.event.issue.body }}
          create_pr: true

