name: "Issue → ブランチ＆PR 自動化"

on:
  issues:
    types: [opened]

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-gemini/gemini-cli-action@v1
        with:
          api_key: ${{ secrets.GEMINI_API_KEY }}
          args: |
            /background Issue内容を解析し、新規 Python モジュール + pytest テストを生成
      - name: Create branch & PR
        run: |
          gh auth login --with-token < <(echo ${{ secrets.GITHUB_TOKEN }})
          gh pr create \
            --title "feat: ${{ github.event.issue.title }}" \
            --body "自動生成 PR\n\nIssue: #${{ github.event.issue.number }}" \
            --base main

