on:
  pull_request:
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: AWS 認証（OIDC）
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "latest"
      - run: |
          terraform fmt -check
          terraform init
          terraform plan -out=tfplan
      - name: プラン結果出力
        run: terraform show -no-color tfplan
